### ISSUE TITLE
Empty Folder

### ISSUE THREAD

**Issue by Qezat** [Marwa-Awad-Ibrahim/poco-MarwaIbrahim#1]
Dear Marwa,

I hope this message finds you well.
You did a great job, but it seems like there's something is missing.

You forgot to create file inside all the folders who's name is README.md which is been asked in the slides.
Please feel free to fix this small issue. ( Tips: You could try to do it by For Loop inside of CLI)

I hope you have a nice day 

Kind regards,
Someone walked by,

**Comment by Marwa-Awad-Ibrahim** [comment]
Dear Qezat
Thank you for your message. 
I will try to fix it , thank you for point this out
Kind regards
Marwa
